# Set this to the mainline branch you are using
trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: setup-azd@0
    displayName: Install azd

  - task: UseDotNet@2
    displayName: "Setup .NET 8"
    inputs:
      version: "8.0.x"

  - pwsh: |
      dotnet workload install aspire
    displayName: Setup .NET Aspire

  - pwsh: |
      if (-not [string]::IsNullOrWhiteSpace($Env:AZURE_CLIENT_ID)) {
        azd auth login `
          --client-id "$Env:AZURE_CLIENT_ID" `
          --federated-credential-provider "github" `
          --tenant-id "$Env:AZURE_TENANT_ID"
      }
    displayName: Log in with Azure (Federated Credentials)

  - pwsh: |
      azd provision --no-prompt
    displayName: Provision Infrastructure
    workingDirectory: ./new-aspire-starter.AppHost/
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)

  - pwsh: |
      azd deploy --no-prompt
    displayName: Deploy Application
    workingDirectory: ./new-aspire-starter.AppHost/
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
      AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
      AZURE_TENANT_ID: $(AZURE_TENANT_ID)

  - pwsh: |
      azd auth logout
    displayName: Cleanup
